[package]
name = "open_segfaults"
version = "0.1.0"
authors = ["jonathan gerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
gdk = "0.10.0"
gio = "0.6.0"

[dependencies.gtk]
features = ["v3_20"]
version="0.6.0"
